using System.Collections.Generic;
using Celo.RandomUser.Data;

namespace Celo.RandomUser
{
    public static class DatabaseInitialSeed
    {
        public static void Seed(RandomUserDbContext context)
        {
            var maleNames = new List<FirstNameMaleSeed>
                {
                    new FirstNameMaleSeed("Ackerley"),
                    new FirstNameMaleSeed("Acton"),
                    new FirstNameMaleSeed("Addison"),
                    new FirstNameMaleSeed("Adney"),
                    new FirstNameMaleSeed("Afton"),
                    new FirstNameMaleSeed("Aiken"),
                    new FirstNameMaleSeed("Albert"),
                    new FirstNameMaleSeed("Alcott"),
                    new FirstNameMaleSeed("Alden"),
                    new FirstNameMaleSeed("Alder"),
                    new FirstNameMaleSeed("Aldrich"),
                    new FirstNameMaleSeed("Aldwin"),
                    new FirstNameMaleSeed("Alford"),
                    new FirstNameMaleSeed("Alfred"),
                    new FirstNameMaleSeed("Alger"),
                    new FirstNameMaleSeed("Allard"),
                    new FirstNameMaleSeed("Almo"),
                    new FirstNameMaleSeed("Alston"),
                    new FirstNameMaleSeed("Alton"),
                    new FirstNameMaleSeed("Alvar"),
                    new FirstNameMaleSeed("Alvin"),
                    new FirstNameMaleSeed("Anscom"),
                    new FirstNameMaleSeed("Ansley"),
                    new FirstNameMaleSeed("Ardley"),
                    new FirstNameMaleSeed("Ardolph"),
                    new FirstNameMaleSeed("Arledge"),
                    new FirstNameMaleSeed("Arley"),
                    new FirstNameMaleSeed("Armstrong"),
                    new FirstNameMaleSeed("Arundel"),
                    new FirstNameMaleSeed("Ascot"),
                    new FirstNameMaleSeed("Ashby"),
                    new FirstNameMaleSeed("Ashford"),
                    new FirstNameMaleSeed("Ashley"),
                    new FirstNameMaleSeed("Ashton"),
                    new FirstNameMaleSeed("Aston"),
                    new FirstNameMaleSeed("Aswin"),
                    new FirstNameMaleSeed("Athelstan"),
                    new FirstNameMaleSeed("Atherton"),
                    new FirstNameMaleSeed("Atley"),
                    new FirstNameMaleSeed("Atwater"),
                    new FirstNameMaleSeed("Atwell"),
                    new FirstNameMaleSeed("Atwood"),
                    new FirstNameMaleSeed("Atworyh"),
                    new FirstNameMaleSeed("Auden"),
                    new FirstNameMaleSeed("Audley"),
                    new FirstNameMaleSeed("Austin"),
                    new FirstNameMaleSeed("Averill"),
                    new FirstNameMaleSeed("Avery"),
                    new FirstNameMaleSeed("Axton")
                };

                var femaleNames = new List<FirstNameFemaleSeed>
                {
                     new FirstNameFemaleSeed("Ada"),
                    new FirstNameFemaleSeed("Adria"),
                    new FirstNameFemaleSeed("Afton"),
                    new FirstNameFemaleSeed("Ailith"),
                    new FirstNameFemaleSeed("Alberta"),
                    new FirstNameFemaleSeed("Aldith"),
                    new FirstNameFemaleSeed("Aldora"),
                    new FirstNameFemaleSeed("Aley"),
                    new FirstNameFemaleSeed("Alfreda"),
                    new FirstNameFemaleSeed("Almena"),
                    new FirstNameFemaleSeed("Alodie"),
                    new FirstNameFemaleSeed("Alura"),
                    new FirstNameFemaleSeed("Alvar"),
                    new FirstNameFemaleSeed("Alverdine"),
                    new FirstNameFemaleSeed("Alvina"),
                    new FirstNameFemaleSeed("Ashley"),
                    new FirstNameFemaleSeed("Audrey"),
                    new FirstNameFemaleSeed("Averil"),
                    new FirstNameFemaleSeed("Avery"),
                    new FirstNameFemaleSeed("Bailey"),
                    new FirstNameFemaleSeed("Beda"),
                    new FirstNameFemaleSeed("Bentley"),
                    new FirstNameFemaleSeed("Berengaria"),
                    new FirstNameFemaleSeed("Bernia"),
                    new FirstNameFemaleSeed("Bertrade"),
                    new FirstNameFemaleSeed("Beverly"),
                    new FirstNameFemaleSeed("Billie"),
                    new FirstNameFemaleSeed("Birdie"),
                    new FirstNameFemaleSeed("Blake"),
                    new FirstNameFemaleSeed("Blessing"),
                    new FirstNameFemaleSeed("Bliss"),
                    new FirstNameFemaleSeed("Blossom"),
                    new FirstNameFemaleSeed("Blythe"),
                    new FirstNameFemaleSeed("Bradley"),
                    new FirstNameFemaleSeed("Brice"),
                    new FirstNameFemaleSeed("Brooke"),
                    new FirstNameFemaleSeed("Cady"),
                    new FirstNameFemaleSeed("Chelsea"),
                    new FirstNameFemaleSeed("Christmas"),
                    new FirstNameFemaleSeed("Claresta"),
                    new FirstNameFemaleSeed("Cleva"),
                    new FirstNameFemaleSeed("Climena"),
                    new FirstNameFemaleSeed("Clover"),
                    new FirstNameFemaleSeed("Cody"),
                    new FirstNameFemaleSeed("Corliss"),
                    new FirstNameFemaleSeed("Courtney"),
                    new FirstNameFemaleSeed("Daisy"),
                    new FirstNameFemaleSeed("Dale"),
                    new FirstNameFemaleSeed("Dana"),
                    new FirstNameFemaleSeed("Daralis"),
                };

                var lastNames = new List<LastNameSeed>
                {
                    new LastNameSeed("Sabo"),
                    new LastNameSeed("Sabol"),
                    new LastNameSeed("Sabori"),
                    new LastNameSeed("Saborido"),
                    new LastNameSeed("Saborio"),
                    new LastNameSeed("Sabot"),
                    new LastNameSeed("Sabota"),
                    new LastNameSeed("Sabourin"),
                    new LastNameSeed("Sacane"),
                    new LastNameSeed("Sacarello"),
                    new LastNameSeed("Sacavage"),
                    new LastNameSeed("Sacayanan"),
                    new LastNameSeed("Sacca"),
                    new LastNameSeed("Saccardi"),
                    new LastNameSeed("Sacchetti"),
                    new LastNameSeed("Sacchi"),
                    new LastNameSeed("Sacco"),
                    new LastNameSeed("Saccone"),
                    new LastNameSeed("Saccucci"),
                    new LastNameSeed("Sachar"),
                    new LastNameSeed("Sache"),
                    new LastNameSeed("Sacher"),
                    new LastNameSeed("Saches"),
                    new LastNameSeed("Sachetti"),
                    new LastNameSeed("Sachez"),
                    new LastNameSeed("Sachleben"),
                    new LastNameSeed("Sachs"),
                    new LastNameSeed("Sachse"),
                    new LastNameSeed("Sachtleben"),
                    new LastNameSeed("Sack"),
                    new LastNameSeed("Sackal"),
                    new LastNameSeed("Sackett"),
                    new LastNameSeed("Sackey"),
                    new LastNameSeed("Sackman"),
                    new LastNameSeed("Sackos"),
                    new LastNameSeed("Sackrider"),
                    new LastNameSeed("Sacks"),
                    new LastNameSeed("Sacramed"),
                    new LastNameSeed("Sacramento"),
                    new LastNameSeed("Sacre"),
                    new LastNameSeed("Sada"),
                    new LastNameSeed("Sadahiro"),
                    new LastNameSeed("Sadak"),
                    new LastNameSeed("Sadan"),
                    new LastNameSeed("Sadar"),
                    new LastNameSeed("Sadat"),
                    new LastNameSeed("Sadberry"),
                    new LastNameSeed("Sadbury"),
                    new LastNameSeed("Saddat"),
                    new LastNameSeed("Saddler"),
                    new LastNameSeed("Sade"),
                    new LastNameSeed("Sadee"),
                    new LastNameSeed("Sadeghi"),
                    new LastNameSeed("Saden"),
                    new LastNameSeed("Sader"),
                    new LastNameSeed("Sadger"),
                    new LastNameSeed("Sadhra"),
                    new LastNameSeed("Sadhu"),
                    new LastNameSeed("Sadik"),
                    new LastNameSeed("Sadin"),
                    new LastNameSeed("Sadiq"),
                    new LastNameSeed("Sadler"),
                    new LastNameSeed("Sadlier"),
                    new LastNameSeed("Sadlon"),
                    new LastNameSeed("Sadlow"),
                    new LastNameSeed("Sadolsky"),
                    new LastNameSeed("Sadorra"),
                    new LastNameSeed("Sadoski"),
                    new LastNameSeed("Sadow"),
                    new LastNameSeed("Sadowski"),
                    new LastNameSeed("Sadowsky"),
                    new LastNameSeed("Sadri"),
                    new LastNameSeed("Sadusky"),
                    new LastNameSeed("Sadvary"),
                    new LastNameSeed("Sae"),
                    new LastNameSeed("Saechao"),
                    new LastNameSeed("Saeed"),
                    new LastNameSeed("Saefong"),
                    new LastNameSeed("Saeger"),
                    new LastNameSeed("Saelee"),
                    new LastNameSeed("Saelens"),
                    new LastNameSeed("Saeler"),
                    new LastNameSeed("Saeli"),
                };

                context.AddRange(maleNames);
                context.AddRange(femaleNames);
                context.AddRange(lastNames);
                context.SaveChanges();
            }
        }
}
